version: '3'
services:
  mongodb:
    image: mongo:3.6.2
    ports:
      - '27017:27017'
    volumes:
      - ./.data/mongodb:/data/db

  server:
    build: .
    restart: always
    env_file:
      - .docker.env
    ports:
      - '4200:4200'

  client:
    build: .
    restart: always
    env_file:
      - .docker.env
    ports:
      - '3000:3000'
