version: '3'
services:
  mongodb:
    image: mongo:3.6.2
    ports:
      - '27017:27017'
    volumes:
      - ./.data/mongodb:/data/db
    networks:
      - mongo

  server:
    build:
      context: '.'
      dockerfile: 'Dockerfile.server'
    env_file:
      - .docker.env
    ports:
      - '4200:4200'
    depends_on:
      - mongodb
    networks:
      - mongo
      - server
      - duct_default

  client:
    build: '.'
    env_file:
      - .docker.env
    ports:
      - '3000:80'
    depends_on:
      - server
    networks:
      - server

networks:
  mongo:
    driver: bridge
  server:
    driver: bridge
  duct_default:
    external: true
