# base
FROM node:11.15-alpine as build

RUN apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python
# To handle 'not get uid/gid'
RUN npm config set unsafe-perm true
RUN npm install --quiet node-gyp -g

WORKDIR /usr/src/app

# install packages
COPY package.json ./
# To handle 'not get uid/gid'
RUN npm config set unsafe-perm true
RUN npm install

# copy src files
COPY server server/
COPY src src/

# expose app on port
EXPOSE 4200

# run
CMD ["sh","-c","npm run run-back"]