export default {
  fontSize: {},
  color: {
    aidsFondsBlue: '#0000ff',
    aidsFondsRed: '#ff0100',
    aidsFondsWhite: '#ffffff',
    toolTipColor: '#414141',
    chartColorOne: '#f2c987',
    chartColorTwo: '#091799',
    chartColorThree: '#CDE9EE',
    zoomGreyZero: '#efefef',
    zoomGreyOne: '#818181',
    zoomGreyTwo: '#505050',
    zoomGreyThree: '#a1a1a1',
    zoomGreyFour: '#dfdfdf',
    zoomGreyFive: '#9b9b9b',
    zoomGreySix: '#cecece',
    zoomGreySeven: '#cfcfcf',
    zoomGreyEight: '#d8d8d8',
    zoomBlack: '#000000',
    colHeadColor: '#9b9b9b',
    errorCellColor: '#ff807f',
    smallTextBlack: '#4a4a4a',
  },
  space: {},
  height: {},
  font: {
    zoomFontFamOne: 'FFMarkProAF-Bold',
    zoomFontFamTwo: 'FFMarkProAF-Book',
  },
  weight: {},
  shadow: {},
  borderRadiu: {},
  icon: {},
};
