version: 2.1
jobs:
  #  CHECKOUT REPOSITORY
  checkout_repo:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/zoom-v2-ui
    steps:
      - checkout
      - attach_workspace:
          at: ~/zoom-v2-ui
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .

  #  BUILD SOURCE AND DEPLOY TO SERVER
  build_deploy:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/zoom-v2-ui
    steps:
      - checkout
      - attach_workspace:
          at: ~/zoom-v2-ui
      - run: sudo apt-get install python-dev
      - run: ./scripts/install-watchman.sh
      - run: yarn relay
      - run:
          name: Set REACT_APP_PROJECT_URL env var
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'export REACT_APP_PROJECT_URL="$REACT_APP_PROJECT_URL_STAGING"' >> $BASH_ENV
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              echo 'export REACT_APP_PROJECT_URL="$REACT_APP_PROJECT_URL_TEST"' >> $BASH_ENV
            elif [ "${CIRCLE_BRANCH}" == "feature" ]; then
              echo 'export REACT_APP_PROJECT_URL="$REACT_APP_PROJECT_URL_DEV"' >> $BASH_ENV
            else
              echo 'export REACT_APP_PROJECT_URL="$REACT_APP_PROJECT_URL_DEV"' >> $BASH_ENV
            fi
            source $BASH_ENV
      - run:
          name: Set REACT_APP_GRAPHQL_HOST and REACT_APP_BACKEND_HOST env var
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'export REACT_APP_GRAPHQL_HOST="$DUCT_STAGING"' >> $BASH_ENV
              echo 'export REACT_APP_BACKEND_HOST="$DUCT_STAGING"' >> $BASH_ENV
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              echo 'export REACT_APP_GRAPHQL_HOST="$DUCT_TEST"' >> $BASH_ENV
              echo 'export REACT_APP_BACKEND_HOST="$DUCT_TEST"' >> $BASH_ENV
            elif [ "${CIRCLE_BRANCH}" == "feature" ]; then
              echo 'export REACT_APP_GRAPHQL_HOST="$DUCT_DEV"' >> $BASH_ENV
              echo 'export REACT_APP_BACKEND_HOST="$DUCT_DEV"' >> $BASH_ENV
            else
              echo 'export REACT_APP_GRAPHQL_HOST="$DUCT_DEV"' >> $BASH_ENV
              echo 'export REACT_APP_BACKEND_HOST="$DUCT_DEV"' >> $BASH_ENV
            fi
            source $BASH_ENV
      - run:
          name: Set REACT_APP_EXPRESS_BACKEND_BASE_URL env var
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'export REACT_APP_EXPRESS_BACKEND_BASE_URL="$REACT_APP_EXPRESS_BACKEND_BASE_URL"' >> $BASH_ENV
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              echo 'export REACT_APP_EXPRESS_BACKEND_BASE_URL="$REACT_APP_EXPRESS_BACKEND_BASE_URL"' >> $BASH_ENV
            elif [ "${CIRCLE_BRANCH}" == "feature" ]; then
              echo 'export REACT_APP_EXPRESS_BACKEND_BASE_URL="$REACT_APP_EXPRESS_BACKEND_BASE_URL"' >> $BASH_ENV
            else
              echo 'export REACT_APP_EXPRESS_BACKEND_BASE_URL="$REACT_APP_EXPRESS_BACKEND_BASE_URL"' >> $BASH_ENV
            fi
            source $BASH_ENV
      - run: yarn build
      - run:
          name: Add target host to known_hosts files
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh-keyscan "$SSH_HOST_STAGING" >> ~/.ssh/known_hosts
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              ssh-keyscan "$SSH_HOST_TEST" >> ~/.ssh/known_hosts
            elif [ "${CIRCLE_BRANCH}" == "feature" ]; then
              ssh-keyscan "$SSH_HOST_DEV" >> ~/.ssh/known_hosts
            else
              ssh-keyscan "$SSH_HOST_DEV" >> ~/.ssh/known_hosts
            fi
      - add_ssh_keys:
          name: Add SSH KEY
          fingerprints:
            - "6f:b2:10:8a:43:db:4b:fb:a0:31:47:da:99:68:7c:af"
      - run: eval ssh-agent -s
      - run: sudo apt install rsync
      - run:
          name: Upload build folder to target host
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              rsync -ave  ssh ~/zoom-v2-ui/build "$SSH_USER"@"$SSH_HOST_STAGING":~/zoom-v2-ui
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              rsync -ave  ssh ~/zoom-v2-ui/build "$SSH_USER"@"$SSH_HOST_TEST":~/zoom-v2-ui
            elif [ "${CIRCLE_BRANCH}" == "feature" ]; then
              rsync -ave  ssh ~/zoom-v2-ui/build "$SSH_USER"@"$SSH_HOST_DEV":~/zoom-v2-ui
            else
              rsync -ave  ssh ~/zoom-v2-ui/build "$SSH_USER"@"$SSH_HOST_DEV":~/zoom-v2-ui
            fi

  test_e2e:
    docker:
      - image: cypress/browsers:chrome67
    working_directory: ~/zoom-v2-ui
    steps:
      - attach_workspace:
          at: ~/zoom-v2-ui
      - run: yarn add cypress
      - run: yarn cy:record

# WORKFLOWS
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - checkout_repo
      - build_deploy:
          requires:
            - checkout_repo
#      - test_e2e:
#          requires:
#            - build_&_deploy
