version: 2
jobs:

  #  CHECKOUT REPOSITORY
  checkout_repo:
    #    machine: true
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/zoom-v2-ui
    steps:
      - checkout
      - attach_workspace:
          at: ~/zoom-v2-ui
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .

  #  CHECKOUT FOR VULNERABILITIES IN LIBRARIES
  check_vulnerabilities:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/zoom-v2-ui
    steps:
      - attach_workspace:
          at: ~/zoom-v2-ui
      - run: yarn validate:dependencies

  #  BUILD SOURCE AND DEPLOY TO SERVER
  build_&_deploy:
    #    machine: true
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/zoom-v2-ui
    steps:
      - checkout
      - attach_workspace:
          at: ~/zoom-v2-ui
      - run: yarn build
      - run: sudo apt install rsync
      - run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - add_ssh_keys:
          name: Add SSH KEY
          fingerprints:
            - "98:09:eb:52:9a:fc:ec:ba:e2:cf:9a:f3:99:0e:a1:e8"
      - run: eval ssh-agent -s
      - run: rsync -ave  ssh ~/zoom-v2-ui/.fusion $SSH_USER@$SSH_HOST:~/zoom-v2-ui/.fusion

  #  EVALUATE BROWSER PERFORMANCE WITH LIGHTHOUSE
  test_performance:
    docker:
      - image: circleci/node:10.13.0-browsers
    working_directory: ~/zoom-v2-ui
    steps:
      - attach_workspace:
          at: ~/zoom-v2-ui
      - run: CI=true yarn lighthouse

  test_e2e:
    docker:
      - image: cypress/browsers:chrome67
    working_directory: ~/zoom-v2-ui
    steps:
      - attach_workspace:
          at: ~/zoom-v2-ui
      - run: yarn add cypress
      - run: yarn cy:record

# WORKFLOWS
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - checkout_repo
      - build_&_deploy:
          requires:
            - checkout_repo
      - test_performance:
          requires:
            - build_&_deploy
#      - test_e2e:
#          requires:
#            - build_&_deploy
